import { LinkIcon } from "@chakra-ui/icons";
import { Box, Container, Heading, Icon, Image } from "@chakra-ui/react";
import React from "react";
import "./tools.css";

import too7img from "../../assets/tool7img.png";
import { Link } from "react-router-dom";
import logo from "../../assets/pcalogo.png";

const Tooll7 = (props) => {
  return (
    <>
      <header className="container">
        <div className="row my-2">
          <div className="col mt-2 col-lg-2 d-flex justify-content-start">
            <div className="" style={{ height: "80px", width: "150px" }}>
              <Link to="/home">
                {!props.logoDisplay ? <></> : <img src={logo} alt="logo" />}
              </Link>
            </div>
          </div>
          <div className="col col-lg-10 " style={{ marginLeft: "-50px" }}>
            <div
              className="d-flex justify-content-start"
              style={{ marginTop: "25px" }}
            >
              <h3>
                Category 3.2 - SPATIAL PLANNING FOR PROTECTED AREAS AND
                PROTECTED AREA SYSTEMS
              </h3>
            </div>
            <h4>
              3.2.2 | PROTECTED AREA SYSTEM PLANNING, INTEGRATED GAP ANALYSIS,
              ZONING
            </h4>
          </div>
        </div>
        <hr className="mt-0" />
      </header>
      <div
        className="container my-5 "
        style={{ width: "800px", backgroundColor: "white", color: "black" }}
      >
        <div className="row fw-bold fs-5 height">
          <div className="col col-md-2 col-sm-2 col-lg-2 border-color bg-fill d-flex  align-items-center">
            TOOL 7
          </div>
          <div className="col col-md-10 col-sm-10 col-lg-10  heading-dark d-flex  align-items-center">
            <a href="https://dopa-explorer.jrc.ec.europa.eu/dopa_explorer">
              DIGITAL OBSERVATORY OF PROTECTED AREAS (DOPA) WITH DOPA EXPLORER
              3.0
            </a>
          </div>
        </div>
        <div className="row ">
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color  fs-10">
            2018
          </div>
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color">
            European Commission Joint Research Centre
          </div>
        </div>
        <div className="row fw-bold ">
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color bg-fill">
            TYPE
          </div>
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color bg-fill">
            PURPOSE
          </div>
        </div>
        <div className="row ">
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color  fs-10">
            Online data and information platform
          </div>
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color">
            Assess, monitor, report and possibly forecast the state of,
            pressures on and other aspects of interest relating to PAs at
            multiple scales.
          </div>
        </div>
        <div className="row border-color fw-bold bg-fill">
          <div className="col ">STRUCTURE AND FUNCTION</div>
        </div>
        <div className="row border-color">
          <div className="col">
            DOPA combines global data on PAs (from{" "}
            <a href="https://protectedplanet.net/">
              ProtectedPlanet <Icon as={LinkIcon} />
            </a>{" "}
            ) with data on species (IUCN Red List), terres-trial and marine
            ecoregions, topography/bathymetry, climate, built-up areas, human
            population, land and forest cover, infrastructure etc. at one
            geo-referenced online platform, in order to enable complex analyses
            of protected areas within their natural and socio-economic context.{" "}
            <br />
            <img src={too7img} alt="" width="100%" />
            (Source: Dubois et al. 2015) <br /> <br />
            <b>DOPA Explorer 3.0</b> allows overlaying these data at the site,
            national and eco-regional level and to evaluate and prioritize sites
            for intervention based on this overlay <br /> <br />
            Typical procedure for data retrieval and analysis using DOPA
            Explorer 3.0: <br />
            <br />
            <ul>
              <li>Open DOPA explorer;</li>
              <li>Choose ecoregion, country or PA of interest;</li>
              <li>Select relevant data categories for area of interest;</li>
              <li>
                Browse, analyse and download information from the report
                generated by DOPA Explorer 3.0;
              </li>
              <li>
                Use data and information to support policy and decision making.
              </li>
            </ul>
          </div>
        </div>
        <div className="row border-color fw-bold bg-fill">
          <div className="col">TYPICAL USE</div>
        </div>
        <div className="row border-color ">
          <div className="col">
            <ul>
              <li>
                Spatial analysis of the state of and pressures on PAs and PA
                systems in support of policy and decision making
              </li>
              <li>
                Comparison and prioritization of PAs within PA systems for
                intervention and investment, based on biodi-versity values,
                pressures, etc.
              </li>
              <li>Monitoring and reporting on PAs at various levels</li>
              <li>
                Access to statistics and other information on specific PAs and
                countries, and comparison between countries
              </li>
            </ul>{" "}
            <br />
            The main intended users of DOPA are the EC, international
            organizations, governments, NGOs and Academia.
          </div>
        </div>
        <div className="row border-color fw-bold bg-fill">
          <div className="col">LEVEL OF APPLICATION</div>
        </div>
        <div className="row border-color ">
          <div className="col">Individual PAs and PA systems, ecoregions</div>
        </div>
        <div className="row border-color fw-bold bg-fill">
          <div className="col">SKILLS AND RESOURCES REQUIRED</div>
        </div>
        <div className="row border-color">
          <div className="col">
            <ul>
              <li>Standard personal computer with internet access</li>
              <li>Basic computer literacy</li>
              <li>Proficiency in English</li>
            </ul>
          </div>
        </div>
        <div className="row border-color fw-bold bg-fill">
          <div className="col col-md-6 col-sm-6 col-lg-6 border ">
            STRENGTHS
          </div>
          <div className="col col-md-6 col-sm-6 col-lg-6 border ">
            WEAKNESSES
          </div>
        </div>
        <div className="row border-color">
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color">
            <ul>
              <li>
                Global geographical coverage and wide thematic coverage;
                combination of various datasets enables effective “deep”
                analysis{" "}
              </li>
              <li>
                Possibility of conducting analysis at various geo-graphical
                scales
              </li>
              <li>
                Easy access and use (without GIS skills) of DOPA Explorer 3.0
              </li>
              <li>Possibility to customize output reports</li>
              <li>Active online support desk</li>
            </ul>
          </div>
          <div className="col col-md-6 col-sm-6 col-lg-6 border-color">
            <ul>
              <li>
                Information on pressures is limited to some defined types of
                pressures only, mainly based on infrastructure and broad proxies
                such as population (e.g. nothing on unsus- tainable natural
                resource use as such)
              </li>
              <li>
                Sometimes incorrect information is entered –e.g. on overlapping
                PAs
              </li>
              <li>
                Quality of analysis depends on input data quality and recentness
                (e.g. on biodiversity, pressures)
              </li>
            </ul>
          </div>
        </div>
        <div className="row border fw-bold bg-fill">
          <div className="col">REFERENCE</div>
        </div>
        <div className="row border-color">
          <div className="col">
            Up to now there is only an introduction to DOPA version 1.0 and a
            short introduction to version 3.0.
          </div>
        </div>
        {/*  */}

        <div className="row border-color">
          <div className="col">
            Dubois, G., L. Bastin, J. Martinez Lopez, A. Cottam, H. Temperley,
            B. Bertzky, M. Graziano (2015).
            <span style={{ textDecoration: "underline", color: "green" }}>
              <a href="https://dopa.jrc.ec.europa.eu/en/documentation">
                The Digital Observatory for Protected Areas (DOPA) Explorer 1.0.
              </a>
            </span>
            EUR 27162 EN. Luxembourg: Publications Office of the European Union.
            53 pp. Accessed on 1 October 2018 at{" "}
            <a href="https://dopa.jrc.ec.europa.eu/en/documentation">
              {" "}
              <Icon as={LinkIcon} />
            </a>
          </div>
        </div>
        <div className="row border-color">
          <div className="col">
            An introduction to DOPA Explorer 3.0 from 2018 gives information
            about the methodology, policy targets (SDGs and Aichi targets),
            improvements to version 2.0, data input and key caveats. Accessed on
            30 Novem-ber 2018 at
            <a href="https://dopa.jrc.ec.europa.eu/sites/default/files/factsheet_3/DOPA%20Factsheet%20A1%20An%20introduction%20to%20DOPA%20Explorer.pdf">
              {"  "}
              <Icon as={LinkIcon} />
            </a>
          </div>
        </div>

        <div className="row border-color fw-bold bg-fill">
          <div className="col">VERSIONS AND/OR MODIFICATIONS</div>
        </div>

        <div className="row border-color">
          <div className="col">
            Earlier Versions of DOPA Explorer: beta, 1.0 and 2.0. <br />
            The current Version DOPA Explorer 3.0 was released in November 2018.{" "}
            <br />
            It is likely that additional updates will be published in the
            future.
          </div>
        </div>

        <div className="row border-color fw-bold bg-fill">
          <div className="col">REVIEWS</div>
        </div>
        <div className="row border-color">
          <div className="col">
            Dubois, G., L. Bastin, B. Bertzky, B. Mandrici, M. Conti, S. Saura,
            A. Cot-tam, L. Battistella, J. Martínez-López, M. Boni, M. Graziano
            (2016).
            <span style={{ textDecoration: "underline", color: "green" }}>
              <a href="http://dx.doi.org/10.3390/rs8100862">
                Integrating multiple spatial datasets to assess protected areas:
                Lessons learnt from the Digital Observatory for Protected Area
                (DOPA). International Journal of Geo-Information 5(12):
              </a>
            </span>
            242. Accessed on 2 October 2018 at{" "}
            <a href="http://dx.doi.org/10.3390/rs8100862">
              <Icon as={LinkIcon} />
            </a>
          </div>
        </div>

        <div className="row border-color fw-bold bg-fill">
          <div className="col">DOCUMENTED EXPERIENCE</div>
        </div>
        <div className="row border-color">
          <div className="col">
            {/*    */}
            Brink, A., J. Martínez-López, Z. Szantoi, P. Moreno-Atencia, A.
            Lupi, L. Bastin, G. Dubois (2016).
            <span style={{ textDecoration: "underline", color: "green" }}>
              <a href="http://dx.doi.org/10.3390/rs8100862">
                Indicators for assessing habitat values, pressures and threats
                for protected areas – an integrated habitat and land cover
                change approach for the Udzungwa Mountains National Park in
                Tanzania. Remote Sensing 8(10):
              </a>
            </span>
            862. Accessed on 2 October 2018 at
            <a href="http://dx.doi.org/10.3390/rs8100862">
              <Icon as={LinkIcon} />
            </a>
          </div>
        </div>

        <div className="row border-color fw-bold bg-fill">
          <div className="col">RELATED RESOURCES/FURTHER READING</div>
        </div>
        <div className="row border-color">
          <div className="col">
            Online information and help desk:{" "}
            <a href="https://ec.europa.eu/jrc/en/contact/form?t=1036">
              <Icon as={LinkIcon} />
            </a>
          </div>
        </div>
        <div className="row border-color">
          <div className="col">
            Information on the Indicators used in DOPA Explorer 3.0 visit{" "}
            <a href="https://dopa.jrc.ec.europa.eu/en/factsheets">
              <Icon as={LinkIcon} />
            </a>
          </div>
        </div>
        <div className="row border-color">
          <div className="col">
            eConservation is a spatial database of conservation (and related
            projects) which is based on DOPA. It is currently available as beta
            version. URL:{" "}
            <a href="https://dopa.jrc.ec.europa.eu/en/applications?qt-applications_qt=1#qt-applications_qt">
              <Icon as={LinkIcon} />
            </a>
          </div>
        </div>
      </div>
    </>
  );
};

export default Tooll7;
